### Predictions for ANN

In [1]:
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model #type: ignore

WARNING:tensorflow:From c:\Users\Aadarsh\miniconda3\envs\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [12]:
# Load the trained model
model = load_model("model.h5")

WARNING:tensorflow:From c:\Users\Aadarsh\miniconda3\envs\venv\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [10]:
# Load the encoder and scaler
with open("onehot_encoding_geography.pkl", "rb") as file:
    onehot_encoder_geo = pickle.load(file)

with open("label_encoder_gender.pkl", "rb") as file:
    label_encoder_gender = pickle.load(file)

with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

In [13]:
# Example input data
input_data = {
    "CreditScore" : 60,
    "Geography" : "France",
    "Gender" : "Male",
    "Age" : 40,
    "Tenure" : 3,
    "Balance" : 60000,
    "NumOfProducts" : 2,
    "HasCrCard" : 1,
    "IsActiveMember" : 1,
    "EstimatedSalary" : 50000
}

In [16]:
# OneHot encode Geography
geo_encoded = onehot_encoder_geo.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))

c:\Users\Aadarsh\miniconda3\envs\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [17]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [20]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,60,France,Male,40,3,60000,2,1,1,50000

In [22]:
# Encode Categorical columns
input_df["Gender"] = label_encoder_gender.transform(input_df["Gender"])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,60,France,1,40,3,60000,2,1,1,50000

In [23]:
# Concatination of OneHot encoded column
input_df = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [24]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,60,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [25]:
# Scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-6.13995993,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [26]:
# Prediction churn
prediction = model.predict(input_scaled)

1/1 [==============================] - 0s 387ms/step

In [27]:
prediction

array([[0.07468237]], dtype=float32)

In [28]:
prediction_prob = prediction[0][0]

In [29]:
prediction_prob

0.07468237

In [30]:
if prediction_prob > 0.5:
    print("The Customer is likely to churn")
else:
    print("The Customer is not likely to churn")

The Customer is not likely to churn