### Salary prediction using Regression

In [27]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential #type: ignore
from tensorflow.keras.layers import Dense #type: ignore
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard #type: ignore
import datetime

In [2]:
data = pd.read_csv("bank.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Preprocessing

In [4]:
# Drop irrelevant columns
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [5]:
# Encode the categorical variables
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])

In [8]:
onehot_encoding_geography = OneHotEncoder(handle_unknown="ignore")
geography_encoded = onehot_encoding_geography.fit_transform(data[["Geography"]])

In [9]:
geo_encoded_df = pd.DataFrame(geography_encoded.toarray(), columns=onehot_encoding_geography.get_feature_names_out(["Geography"])) #type: ignore

In [10]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [11]:
# Combine all the columns with original data
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [12]:
# Split the data into features and target
X = data.drop("EstimatedSalary", axis=1)
y = data["EstimatedSalary"]

In [17]:
# Save the encoders and scaler 
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)
    
with open("onehot_encoding_geography.pkl", "wb") as file:
    pickle.dump(onehot_encoding_geography, file)

In [14]:
# Split the data in train and test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
# Scale the feaures
scaler = StandardScaler()

In [16]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

### ANN Regression

In [22]:
# Build our ANN model
model = Sequential(
    [
        Dense(64, activation="relu", input_shape=(X_train.shape[1],)), #type: ignore
        Dense(32, activation="relu"),
        Dense(1),
    ]
)

In [24]:
# Compile the model
model.compile(optimizer="adam", loss="mean_absolute_error", metrics=["mae"])

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Setup the Tensorboard
log_dir = "regression_logs/fit/" + datetime.datetime.now().strftime("%d%m%Y-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [29]:
# Setup Early stopping
early_stopping_callback = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

In [30]:
# Training the model
history = model.fit(
    X_train, y_train, 
    validation_data=(X_test, y_test), 
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Aadarsh\miniconda3\envs\venv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Aadarsh\miniconda3\envs\venv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 5ms/step - loss: 100373.8047 - mae: 100373.8047 - val_loss: 98500.1250 - val_mae: 98500.1250
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99554.7891 - mae: 99554.7891 - val_loss: 96828.4531 - val_mae: 96828.4531
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96611.2422 - mae: 96611.2422 - val_loss: 92458.7422 - val_mae: 92458.7422
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 90809.5859 - mae: 90809.5859 - val_loss: 85244.6094 - val_mae: 85244.6094
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 82495.9609 - mae: 82495.9609 - val_loss: 76127.2422 - val_mae: 76127.2422
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 73047.9297 - mae: 73047.9297 - val_loss: 67117.7109 - val_mae: 67117.7109
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 64333.7031 - mae: 64333.7031 - val_loss: 59743.7969 - val_mae: 59743.7969
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 57892.7969 - mae: 57892.7969 - val_loss: 54790.1250 - val_mae: 54790.1250
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 53907.0625 - mae: 53907.0625 - val_loss: 52170.8711 - val_mae: 52170.8711
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 51877.6172 - mae: 51877.6172 - val_loss: 51124.8320 - val_mae: 51124.8320
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50971.5391 - mae: 50971.5391 - val_loss: 50760.2344 - val_mae: 50760.2344
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50558.0977 - mae: 50558.0977 - val_loss: 50580.0391 - val_mae: 50580.0391
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50358.9336 - mae: 50358.9336 - val_loss: 50489.6875 - val_mae: 50489.6875
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50245.2344 - mae: 50245.2344 - val_loss: 50438.2891 - val_mae: 50438.2891
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50163.5430 - mae: 50163.5430 - val_loss: 50398.8242 - val_mae: 50398.8242
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50105.1211 - mae: 50105.1211 - val_loss: 50372.2344 - val_mae: 50372.2344
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50052.0938 - mae: 50052.0938 - val_loss: 50343.3750 - val_mae: 50343.3750
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50005.6758 - mae: 50005.6758 - val_loss: 50322.2617 - val_mae: 50322.2617
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 49969.8398 - mae: 49969.8398 - val_loss: 50306.7969 - val_mae: 50306.7969
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49935.7305 - mae: 49935.7305 - val_loss: 50282.6484 - val_mae: 50282.6484
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49909.1406 - mae: 49909.1406 - val_loss: 50270.9727 - val_mae: 50270.9727
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49882.2227 - mae: 49882.2227 - val_loss: 50263.2734 - val_mae: 50263.2734
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49856.0547 - mae: 49856.0547 - val_loss: 50248.9805 - val_mae: 50248.9805
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49826.6484 - mae: 49826.6484 - val_loss: 50238.7227 - val_mae: 50238.7227
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49806.2031 - mae: 49806.2031 - val_loss: 50227.1094 - val_mae: 50227.1094
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49785.8945 - mae: 49785.8945 - val_loss: 50218.1133 - val_mae: 50218.1133
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49764.2227 - mae: 49764.2227 - val_loss: 50208.2812 - val_mae: 50208.2812
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49745.0781 - mae: 49745.0781 - val_loss: 50203.9766 - val_mae: 50203.9766
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49727.9258 - mae: 49727.9258 - val_loss: 50195.0703 - val_mae: 50195.0703
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49712.0742 - mae: 49712.0742 - val_loss: 50181.0781 - val_mae: 50181.0781
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49696.8672 - mae: 49696.8672 - val_loss: 50188.5469 - val_mae: 50188.5469
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49680.1562 - mae: 49680.1562 - val_loss: 50177.9141 - val_mae: 50177.9141
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49663.8203 - mae: 49663.8203 - val_loss: 50178.9922 - val_mae: 50178.9922
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49654.0000 - mae: 49654.0000 - val_loss: 50171.4922 - val_mae: 50171.4922
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49639.8594 - mae: 49639.8594 - val_loss: 50161.6406 - val_mae: 50161.6406
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49630.2773 - mae: 49630.2773 - val_loss: 50167.0352 - val_mae: 50167.0352
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49616.2617 - mae: 49616.2617 - val_loss: 50180.2812 - val_mae: 50180.2812
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49604.6523 - mae: 49604.6523 - val_loss: 50177.6172 - val_mae: 50177.6172
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49589.5000 - mae: 49589.5000 - val_loss: 50172.9336 - val_mae: 50172.9336
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49580.9609 - mae: 49580.9609 - val_loss: 50165.5508 - val_mae: 50165.5508
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49571.0078 - mae: 49571.0078 - val_loss: 50177.3594 - val_mae: 50177.3594
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49564.4805 - mae: 49564.4805 - val_loss: 50162.3633 - val_mae: 50162.3633
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49553.7734 - mae: 49553.7734 - val_loss: 50169.1094 - val_mae: 50169.1094
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49547.0000 - mae: 49547.0000 - val_loss: 50157.8047 - val_mae: 50157.8047
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49535.8164 - mae: 49535.8164 - val_loss: 50159.9766 - val_mae: 50159.9766
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49527.2695 - mae: 49527.2695 - val_loss: 50168.3672 - val_mae: 50168.3672
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49522.2109 - mae: 49522.2109 - val_loss: 50165.4297 - val_mae: 50165.4297
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49516.4453 - mae: 49516.4453 - val_loss: 50156.3711 - val_mae: 50156.3711
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49506.3945 - mae: 49506.3945 - val_loss: 50168.0000 - val_mae: 50168.0000
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49502.4609 - mae: 49502.4609 - val_loss: 50161.9922 - val_mae: 50161.9922
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49491.8203 - mae: 49491.8203 - val_loss: 50167.0664 - val_mae: 50167.0664
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49485.0156 - mae: 49485.0156 - val_loss: 50161.7969 - val_mae: 50161.7969
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49479.1758 - mae: 49479.1758 - val_loss: 50163.4414 - val_mae: 50163.4414
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49476.0391 - mae: 49476.0391 - val_loss: 50164.4258 - val_mae: 50164.4258
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49469.6055 - mae: 49469.6055 - val_loss: 50160.5000 - val_mae: 50160.5000
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49461.6016 - mae: 49461.6016 - val_loss: 50168.6133 - val_mae: 50168.6133
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49459.0977 - mae: 49459.0977 - val_loss: 50165.4766 - val_mae: 50165.4766
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49452.9961 - mae: 49452.9961 - val_loss: 50166.2383 - val_mae: 50166.2383

In [31]:
%load_ext tensorboard

In [34]:
%tensorboard --logdir regression_logs/fit

Reusing TensorBoard on port 6007 (pid 19576), started 0:00:06 ago. (Use '!kill 19576' to kill it.)

In [35]:
# Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae}")
print(f"Test loss: {test_loss}")

63/63 [==============================] - 0s 2ms/step - loss: 50156.3711 - mae: 50156.3711
Test MAE: 50156.37109375
Test loss: 50156.37109375

In [36]:
model.save("regression_model.h5")

c:\Users\Aadarsh\miniconda3\envs\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(